# Generated by Django 3.1 on 2020-08-31 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20200831_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='todos',
        ),
        migrations.AddField(
            model_name='todo',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todoapp.project'),
            preserve_default=False,
        ),
    ]
