# Generated by Django 3.1.1 on 2020-09-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='id',
            field=models.CharField(default='145712', max_length=10, primary_key=True, serialize=False),
        ),
    ]
