# Generated by Django 3.1.1 on 2020-09-05 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_auto_20200905_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 16, 2, 33, 67557), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invite',
            name='expire_time',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='invite',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 14, 16, 3, 14, 669949), editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invite',
            name='id',
            field=models.CharField(default='BB5B80', max_length=10, primary_key=True, serialize=False),
        ),
    ]
