# Generated by Django 3.1.1 on 2020-09-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_auto_20200905_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='valid_until',
        ),
        migrations.AlterField(
            model_name='invite',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='id',
            field=models.CharField(default='133768', max_length=10, primary_key=True, serialize=False),
        ),
    ]
