# Generated by Django 3.1.1 on 2020-09-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_auto_20200905_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
